# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0822783b57c720e342a5a7a2c941c20191c8ed23978527c1858f64a59b138e83fb9d1c38782af255af887f71aeba576ae645299d3cf5aca8c6c76770c49840

test:
  secret_key_base: 3775ca6f6faa2220436104ec3202c29b078b31339e1e514778185b723c00a0d4417ac22aa4559372f36778c4677033e2d8e92b86cb514f307b5777439004707e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
